name: tailwindcss_docs_alfred_workflow
description: Search the Tailwind CSS documentation using Alfred

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 2.3.3

environment:
  sdk: ^3.4.0

dependencies:
  alfred_workflow: ^1.1.3
  algoliasearch: ^1.30.2
  args: ^2.7.0
  cli_script: ^1.0.0
  collection: ^1.19.1
  envied: ^1.1.1
  html_unescape: ^2.0.0
  json_annotation: ^4.9.0
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  json_serializable: ^6.11.1
  lints: ^5.1.1
