name: tailwindcss_docs_alfred_workflow
description: Search the Tailwind CSS documentation using Alfred

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 2.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  algolia: ^1.0.4
  args: ^2.3.0
  html_unescape: ^2.0.0
  alfred_workflow:
    git:
      url: git@github.com:techouse/alfred_workflow.git
      ref: master
  collection: ^1.16.0

dev_dependencies:
  lints: ^1.0.0
  dart_code_metrics: ^4.8.1
